vRotacion: 0.157079
vAvance: 10.0
vidaMax: 100
balasPorRafagaAmetralladora: 5
balasPorRafagaCanion: 1
balasPorRafagaPistola: 1
maxBalas: 25
cantidadBalasInicial: 8
distanciaMaxAcuchillable: 20.0
puntos_cruz: 10.0
punto_copa: 50.0
punto_cofre: 100.0
puntos_corona: 200.0
cantidadVidas: 2
puntos_balas: 5
puntos_matar: 10
danio_maximo_arma: 10
puntosVidaComida: 10
balasEnMapas: 5
puntosVidaKits: 20
puntosVidaSangre: 1