port: 8080
rutaMapas:
mapas:
  - name: mapa1
    file: mapa1.yaml
  - name: mapa2
    file: mapa2.yaml
  - name: mapa3
    file: mapa3.yaml
  - name: mapa4
    file: mapa4.yaml
  - name: mapa5
    file: mapa5.yaml
  - name: mapa6
    file: mapa6.yaml
  - name: mapa7
    file: mapa7.yaml
vRotacion:
vAvance:
vidaMax:
balasPorRafaga:
maxBalas:
